server:
  port: 8080
spring:
  application:
    name: BBLService
  datasource:
    url: jdbc:mysql://localhost:3306/bbl?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2222